/* This file is automatically generated */
#ifndef __UF_WIN_VER_H__
#define __UF_WIN_VER_H__

#define UNIFI_MAJOR_VERSION     7
#define UNIFI_MINOR_VERSION     0
#define UNIFI_REVISION          0
#define UNIFI_BUILD_ID          191

#endif /* __UF_WIN_VER_H__ */
